language: C
dist: bionic
sudo: false

addons:
  apt:
    packages:
    - original-awk
    - gawk

install:
  - original-awk --version
  - gawk --version | head -n 1

script: ./test-runner.sh

env:
  matrix:
    - AWK=original-awk
    - AWK=gawk
