language: C
dist: trusty
sudo: false

addons:
  apt:
    packages:
    - original-awk
    - gawk

install:
  - original-awk --version
  - gawk --version | head -n 1

script: ./travis-test-all.sh

env:
  matrix:
    - AWKCMD=original-awk
    - AWKCMD=gawk
